### ISSUE TITLE
Feature request

### ISSUE THREAD

**Issue by mostafaAbdelazim** [JagarYousef/ChatVoicePlayer#1]
Add support for RTL layouts

**Comment by MH3sham** [comment]
I need that too, Or maybe add an option to change the play button icon so we can add an auto mirrored asset.

**Comment by JagarYousef** [comment]
@mostafaAbdelazim I was thinking about this but I found out that all players seek bars are LTR even if the language is RTL

**Comment by JagarYousef** [comment]
@MH3sham  you may try with setters since there are setters for every component.
```
chatVoicePlayer.setImgPlay(imgView1);
chatVoicePlayer.setImgPause(imgView2);
chatVoicePlayer.setImgShare(imgView3);
```

**Comment by MH3sham** [comment]
@JagarYousef Great. Thanks for your work.
