### ISSUE TITLE
question about main thread issue

### ISSUE THREAD

**Issue by fukemy** [JagarYousef/ChatVoicePlayer#12]
hi, i see you using stream in FileUtils
```
public static byte[] fileToBytes(File file) {
        int size = (int) file.length();
        byte[] bytes = new byte[size];
        try {
            BufferedInputStream buf = new BufferedInputStream(new FileInputStream(file));
            buf.read(bytes, 0, bytes.length);
            buf.close();
        } catch (FileNotFoundException e) {
            e.printStackTrace();
        } catch (IOException e) {
            e.printStackTrace();
        }
        return bytes;
    }
```

i want to ask if I using url from network, and my recyclerview have many voice, so did it block main thread and cause delay? Thanks

**Comment by JagarYousef** [comment]
Please try with the last version, this should be fixed now

**Comment by fukemy** [comment]
Thanks for your update

i saw you using asynctask to get media data, but i know asynctask is deprecated now, it's also have max threadpool , so i user have to load many media data at once time, does it work normally? Thanks
