### ISSUE TITLE
mediaplayer block mainthread when preparing

### ISSUE THREAD

**Issue by fukemy** [JagarYousef/ChatVoicePlayer#14]
hi, i have multi cell as VoicePlayerView, and i saw that took a lot of time to display all? Do you have any solution?

**Comment by fukemy** [comment]
using prepareAsync but still laggy when scroll recyclerview, i decide to remove this lib

**Comment by fukemy** [comment]
after saw u update this lib, please help this problem, this is the biggest problem when using this lib with recyclerview

**Comment by GovindHiteshi** [comment]
Hii sir 
I'm also face this error 
if you have any solution please tell me

**Comment by fukemy** [comment]
bro, i still stuck on this, the biggest problem based on this code:
```
//START and PAUSE are in other listeners
                mediaPlayer.setOnPreparedListener(new MediaPlayer.OnPreparedListener() {
                    @Override
                    public void onPrepared(MediaPlayer mp) {
                        seekBar.setMax(mp.getDuration());
                        if (seekbarV.getVisibility() == VISIBLE){
                            seekbarV.setMax(mp.getDuration());
                        }
                        txtProcess.setText(convertSecondsToHMmSs(mp.getDuration() / 1000));
                    }
                });
```

***setOnPreparedListener*** block main thread, im working on IOS, i will back to android later
