### ISSUE TITLE
when I add the library to dependencies I get this error when building Manifest merger failed with multiple errors, see logs

### ISSUE THREAD

**Issue by mohamed-hesham1** [JagarYousef/ChatVoicePlayer#15]
when I add the library to dependencies I get this error "when building Manifest merger failed with multiple errors, see logs"

**Comment by mohamed-hesham1** [comment]
![image](https://user-images.githubusercontent.com/80651511/126700090-081e401b-2640-47b3-b1bd-5ab662279006.png)

**Comment by mohamed-hesham1** [comment]
put this on your manifest file in application and it will work    android:appComponentFactory="androidx.core.app.CoreComponentFactory"

**Comment by JagarYousef** [comment]
I saw you solved it, many thanks for sharing!
