### ISSUE TITLE
sound not stop when close the app using adapter

### ISSUE THREAD

**Issue by waleedocp** [JagarYousef/ChatVoicePlayer#2]
i use this library in adapter when i press back the sound didn't stop

**Comment by JagarYousef** [comment]
You can work around using the following: 
1- Make an ArrayList<MediaPlayer> in your adapter.
2- Add all ChatVoicePlayer's MediaPlayers to the list when binding them; you can get one by` chatVoicePlayer.getMediaPlayer();`
3- No override onPaues() in the adapter():
```
@Override
public void onPause(){
    for(MediaPlayer mp : mediaPlayersList){
       if (mp != null && mp.isPlaying()) {
          mp.stop(); // or mp.pause();
           mp.release();
        }
    super.onPause();
}
```
