### ISSUE TITLE
Progress bar stopped showing

### ISSUE THREAD

**Issue by ChrisLMills** [JagarYousef/ChatVoicePlayer#3]
I have implemented the ChatVoicePlayer successfully. At first I could see the progress bar, then I couldn't. I didn't make changes to the XML. Any idea what could be causing this?

To add, it still works, I can move it up and down,  and I can also see the click animation on it.

**Comment by JagarYousef** [comment]
Hi @ChrisLMills 
Did you check colors ?

```
 app:visualizationPlayedColor="#VALUE"
 app:visualizationNotPlayedColor="#VALUE""
 app:playPauseBackgroundColor="#VALUE""
 app:timingBackgroundColor="#VALUE""
 app:seekBarProgressColor="#VALUE""
```

**Comment by ChrisLMills** [comment]
Hi @JagarYousef 

I remember checking colours, but I would like to double check before confirming. 
I'll only be able to do this next week though.
I'll keep you updated.

**Comment by JagarYousef** [comment]
Thank you, I am closing this due to it is not active anymore
Please feel free to reopen when there is a need or update
