### ISSUE TITLE
ChatVoicePlayer continuously calling custom method once play is pressed

### ISSUE THREAD

**Issue by ChrisLMills** [JagarYousef/ChatVoicePlayer#4]
I've integrated ChatVoicePlayer into a chat recycler view. 

I have a method that checks the content in each recycler view item to be able to handle it in a specific way. However, any item that contains the ChatVoicePlayer calls this method continuously once play is pressed, and even after paused, or even the activity closed.

Is there anything under the hood of the ChatVoicePlayer that could be triggering this?

**Comment by JagarYousef** [comment]
Hi @ChrisLMills 
I am not sure if I got it well but can you please check this one #2

**Comment by ChrisLMills** [comment]
Hi @JagarYousef 

Yes, I did check #2 and that is fixed. 

Have you replicated this issue?

**Comment by JagarYousef** [comment]
Great, thank you

**Comment by fukemy** [comment]
hi @ChrisLMills, how did u solved that? I tried to implement onPause method in recyclerView + recyclerView Adapter but can not find this method to override

**Comment by fukemy** [comment]
thanks, but i think we all have to face the "audio cell scroll problem", i think using mediaPlayer to first get duration is best choice, but the problem is when scroll fast recyclerView it make laggy, did u faced this?

**Comment by fukemy** [comment]
or if you have better library, please share with me, thanks buddy
